USE [master]
GO
/****** Object:  Database [VAC]    Script Date: 16-Jun-19 20:00:12 ******/
CREATE DATABASE [VAC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VAC', FILENAME = N'/var/opt/mssql/data/VAC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VAC_log', FILENAME = N'/var/opt/mssql/data/VAC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [VAC] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VAC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VAC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VAC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VAC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VAC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VAC] SET ARITHABORT OFF 
GO
ALTER DATABASE [VAC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VAC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VAC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VAC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VAC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VAC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VAC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VAC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VAC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VAC] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VAC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VAC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VAC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VAC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VAC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VAC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VAC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VAC] SET RECOVERY FULL 
GO
ALTER DATABASE [VAC] SET  MULTI_USER 
GO
ALTER DATABASE [VAC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VAC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VAC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VAC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VAC] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'VAC', N'ON'
GO
ALTER DATABASE [VAC] SET QUERY_STORE = OFF
GO
USE [VAC]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[UserID] [int] NOT NULL,
	[OS Name] [nvarchar](20) NULL,
	[OS Version] [nvarchar](20) NULL,
	[Device Brand] [nvarchar](50) NULL,
	[Device Model] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Logs]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logs](
	[ServerID] [int] NOT NULL,
	[Type] [nvarchar](20) NOT NULL,
	[Event] [nvarchar](40) NOT NULL,
	[Content] [nvarchar](200) NULL,
	[Date] [datetime] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Servers]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Servers](
	[ServerID] [int] NOT NULL,
	[OS Name] [nvarchar](50) NULL,
	[OS Version] [nvarchar](20) NULL,
	[Python Version] [nvarchar](10) NULL,
	[Node Name] [nvarchar](50) NULL,
	[CPU] [nvarchar](100) NULL,
	[Memory Size] [int] NULL,
 CONSTRAINT [PK_Servers_ServerID] PRIMARY KEY CLUSTERED 
(
	[ServerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Servers_ServerID] UNIQUE NONCLUSTERED 
(
	[ServerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sessions]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sessions](
	[SessionID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[ServerID] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_Sessions_SessionID] PRIMARY KEY CLUSTERED 
(
	[SessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Sessions_SessionID] UNIQUE NONCLUSTERED 
(
	[SessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Statistics]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Statistics](
	[SessionID] [int] NOT NULL,
	[Name] [nvarchar](64) NOT NULL,
	[Value] [nvarchar](128) NOT NULL,
	[Date] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Test_Table]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test_Table](
	[Test1] [nvarchar](50) NULL,
	[Test2] [nvarchar](50) NULL,
	[Test3] [nvarchar](50) NULL,
	[Test4] [nvarchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 16-Jun-19 20:00:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] NOT NULL,
	[Login] [nvarchar](128) NOT NULL,
	[Password] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_Users_UserID] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_UserID] UNIQUE NONCLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Users_UserID] UNIQUE NONCLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Client]  WITH CHECK ADD  CONSTRAINT [FK_Client_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Client] CHECK CONSTRAINT [FK_Client_Users]
GO
ALTER TABLE [dbo].[Logs]  WITH CHECK ADD  CONSTRAINT [FK_Entries_Servers] FOREIGN KEY([ServerID])
REFERENCES [dbo].[Servers] ([ServerID])
GO
ALTER TABLE [dbo].[Logs] CHECK CONSTRAINT [FK_Entries_Servers]
GO
ALTER TABLE [dbo].[Sessions]  WITH CHECK ADD  CONSTRAINT [FK_Sessions_Servers] FOREIGN KEY([ServerID])
REFERENCES [dbo].[Servers] ([ServerID])
GO
ALTER TABLE [dbo].[Sessions] CHECK CONSTRAINT [FK_Sessions_Servers]
GO
ALTER TABLE [dbo].[Sessions]  WITH CHECK ADD  CONSTRAINT [FK_Sessions_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Sessions] CHECK CONSTRAINT [FK_Sessions_Users]
GO
ALTER TABLE [dbo].[Statistics]  WITH CHECK ADD  CONSTRAINT [FK_Statistics_Sessions] FOREIGN KEY([SessionID])
REFERENCES [dbo].[Sessions] ([SessionID])
GO
ALTER TABLE [dbo].[Statistics] CHECK CONSTRAINT [FK_Statistics_Sessions]
GO
USE [master]
GO
ALTER DATABASE [VAC] SET  READ_WRITE 
GO
